### ISSUE TITLE
The scheduled trigger in this application doesn't work; do we want to keep it?

### ISSUE THREAD

**Issue by filmaj** [slack-samples/deno-virtual-running-buddies#14]
I believe because the scheduled trigger definition uses trigger data like `interactivity` and `channel` that do not exist on scheduled triggers; scheduled triggers are neither interactive nor do they necessarily have an associated channel with them.

If I understand the intention of the scheduled trigger in this app, it is to post the leaderboard on a regular cadence in a channel somewhere. I think to enable this pattern, we would need to implement a "configure" workflow where a user can "configure" this scheduled trigger to post in a specific channel of their choosing. Then this workflow would dynamically create a scheduled trigger using a custom function, setting the channel chosen by the user as an input into the display leaderboard workflow.

Alternatively, can consider removing the scheduled trigger altogether.

**Comment by zimeg** [comment]
Good callouts with the trigger inputs, I'll make an update to remove `interactivity` but think we can still keep a `channel` input that's configured with environment variables.

The configurator workflow pattern feels a bit complex for this sample as I imagine there would be a primary `#runners` channel for these stats to be posted to, but that's just an assumption! I'm unsure if there's another sample that showcases environment variables in a trigger definition, so this might also be a good opportunity for that?

Going to start work on the updating PR but absolutely no worries if you think the configuring workflow (or removing this trigger altogether) makes more sense!
